name: Continuous Integration

on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*

env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "3.0"
            appraisal: "http_5"
          - ruby: "2.7"
            appraisal: "http_4"
          - ruby: "2.5"
            appraisal: "http_3"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set Appraisal bundle
      if: matrix.appraisal != ''
      run: |
        echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
        bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
    - name: Install gems
      run: |
        bundle install
    - name: Run Tests
      run: bundle exec rake
    - name: Run standardrb
      if:   matrix.standardrb == true
      run:  bundle exec rake standard
